pythonspeed/filprofiler

- .github/workflows/main.yml
- Makefile
> Minimal CI: run tests on PRs

- .changelog/15.feature
- .github/workflows/main.yml
- Makefile
- filprofiler/_filpreload.c
- filprofiler/_script.py
- filprofiler/_tracer.py
- filprofiler/design/allocator-overrides.md
- filprofiler/interpose.h
- filprofiler/licenses.txt
- filprofiler/tests/test_utils.py
- python-benchmarks/printer.py
- python-benchmarks/write-to-file.py
- setup.py
- tests/test_endtoend.py
> macOS support

- .github/workflows/main.yml
- Makefile
- RELEASING.md
- setup.py
- wheels/build-wheels.sh
Upload wheels to PyPI if tag is set.
Fixes #19.
> Release automation

- filprofiler/_report.py
> Include bug reporting link in report.

- .changelog/36.bugfix
- filprofiler/_filpreload.c
> Don't load aligned_alloc on macOS

- .changelog/43.bugfix
- memapi/src/memorytracking.rs
Fixes #43.
We can still do much better by also switching to OrdMap, so will open followup ticket.
> Reduce tracking memory overhead

- .changelog/38.bugfix
- memapi/src/memorytracking.rs
> Reduce report generation memory use

- .changelog/47.feature
- .github/workflows/main.yml
- memapi/src/memorytracking.rs
> Compress allocation sizes, reducing tracking overhead

- .changelog/61.feature
- README.md
- filprofiler/_filpreload.c
- memapi/src/lib.rs
- memapi/src/memorytracking.rs
- python-benchmarks/ldpreload.py
- python-benchmarks/malloc.py
- python-benchmarks/pymalloc.pyx
- tests/test_endtoend.py
> posix_memalign() support

- .changelog/20.feature
- Makefile
- README.md
- requirements-dev.txt
- setup.py
- tests/test_endtoend.py
> Conda-Forge packages

- python-benchmarks/ldpreload.py
- requirements-dev.txt
> Work around bug in nbconvert

- README.md
> Better explanation of what Fil does and how it differs

- .changelog/99.bugfix
- Makefile
- filprofiler/_filpreload.c
- python-benchmarks/malloc_on_thread_exit.c
- python-benchmarks/thread_exit.py
- tests/test_endtoend.py
> Fix core dump on thread exit when thread-local storage destructor allocates/frees memory

- .changelog/102.bugfix
- memapi/proptest-regressions/memorytracking.txt
- memapi/src/memorytracking.rs
> Reduce flamegraph memory usage

- .changelog/108.minor
- .github/workflows/main.yml
- Makefile
- filprofiler/_filpreload.c
- filprofiler/_tracer.py
- memapi/src/memorytracking.rs
- memapi/src/rangemap.rs
> Clean up internal state between runs in way that doesn't make it invalid

- .changelog/71.feature
- README.md
- filprofiler/__init__.py
- filprofiler/_ipython.py
- filprofiler/_script.py
- filprofiler/_tracer.py
- filprofiler/api.py
- tests/test-scripts/fil-interpreter.py
- tests/test-scripts/jupyter.ipynb
- tests/test_endtoend.py
Fixes #71 
@ChaimBlau @corleyma would appreciate your feedback about whether this meets your needs.
> Public API for profiling, as alternative to CLI

- memapi/src/memorytracking.rs
More support for production version of Fil.
> Make removed size available to caller

- .changelog/136.bugfix
- .flake8
- Makefile
- filprofiler/_cachegrind.py
- filprofiler/_filpreload.c
- filprofiler/_ipython.py
- filprofiler/_script.py
- filprofiler/tests/test_report.py
- filprofiler/tests/test_utils.py
- requirements-dev.txt
> Fewer spurious warnings

- .changelog/135.bugfix
- filprofiler/_filpreload.c
> Fix for breakage on macOS

- .changelog/133.bugfix
- .github/workflows/main.yml
- filprofiler/_filpreload.c
- filprofiler/_script.py
- filprofiler/_tracer.py
- filprofiler/_utils.py
- tests/test_endtoend.py
Supposed to fix #133, but user reports it did not solve the problem.
> Use ld.so when possible

- .changelog/133.feature
- Makefile
- filprofiler/__init__.py
- filprofiler/_filpreload.c
- filprofiler/_script.py
- filprofiler/_tracer.py
- filprofiler/api.py
- tests/test-scripts/fil-interpreter.py
- tests/test-scripts/fil_api.py
- tests/test_endtoend.py
> Better error messages when trying to use API in subprocesses

- .changelog/144.bugfix
- filpreload/src/lib.rs
- memapi/src/oom.rs
> Fix (or at least improve) OOM detection on Linux

- .changelog/156.bugfix
- filprofiler/_filpreload.c
> Use atomic switch

- .changelog/154.bugfix
- memapi/src/memorytracking.rs
- memapi/src/util.rs
> Better debug output for missing allocations

- .changelog/59.feature
- README.md
- filprofiler/_script.py
- filprofiler/_tracer.py
> Add --no-browser option and related documentation

- .changelog/149.bugfix
- filprofiler/_filpreload.c
> Add missing reentrancy prevention

- .changelog/170.bugfix
- filprofiler/_filpreload.c
> Fix a race condition in tracking metadata

- .changelog/179.bugfix
- filpreload/src/lib.rs
- filprofiler/_filpreload.c
- memapi/src/memorytracking.rs
> Don't stop tracking during thread startup or shutdown.

- .changelog/167.bugfix
- filprofiler/_ipython.py
- tests/test-scripts/jupyter.ipynb
> Don't lose locals defined inside a `%%filprofile` magic cell in Jupyter/IPython

- Cargo.lock
- filpreload/Cargo.toml
- filpreload/src/_filpreload.c
- filpreload/src/lib.rs
- memapi/Cargo.toml
- memapi/src/ffi.rs
- memapi/src/lib.rs
- memapi/src/mmap.rs
> Working munmap() wrapper that does more in Rust and less in C.

- .changelog/202.bugfix
- filprofiler/_script.py
- filprofiler/_tracer.py
- memapi/src/memorytracking.rs
- memapi/src/python.rs
- requirements-dev.txt
- tests/test_endtoend.py
> Support Apache Beam

- .changelog/201.feature
- README.md
- filpreload/src/lib.rs
- filprofiler/_script.py
- memapi/src/oom.rs
- tests/test_endtoend.py
> Option to disable oom detection

- Cargo.lock
- filpreload/Cargo.toml
- memapi/Cargo.toml
- memapi/src/memorytracking.rs
> Update to PyO3 0.14.

- .changelog/215.bugfix
- filpreload/src/_filpreload.c
> Fixes for bad reentrancy logic

- .changelog/237.bugfix
- filpreload/src/_filpreload.c
- filpreload/src/lib.rs
- filprofiler/_script.py
- filprofiler/_testing.py
- tests/test-scripts/sigusr2.py
- tests/test_endtoend.py
> Fix SIGUSR2 so it works again as expected

- benchmarks/image-translate.py
- filpreload/build.rs
- filpreload/export_symbols.txt
- filprofiler/_report.py
- memapi/src/flamegraph.rs
- memapi/src/lib.rs
- memapi/src/memorytracking.rs
- memapi/src/oom.rs
- setup.py
Originally part of the abandoned performance profiling branch.
> Refactor out the flamegraph code, and other minor improvements

- .changelog/253.bugfix
- .github/workflows/main.yml
- pyproject.toml
> Build macOS wheels with cibuildwheel

- .changelog/268.feature
- pyproject.toml
> 3.10 wheels on macOS.

- CHANGELOG.md
- docs/src/SUMMARY.md
- docs/src/fil/changelog.md
- filprofiler/_utils.py
- filprofiler/tests/test_script.py
> Support wierd glibc versions

- .changelog/302.bugfix
- Cargo.lock
- filpreload/Cargo.toml
- filpreload/src/lib.rs
> Switch to maintained jemalloc package

- .changelog/334.bugfix
- .changelog/336.bugfix
- filprofiler/_tracer.py
- filprofiler/_utils.py
Fixes #336 
Workaround for #334
> A couple small improvements

- filpreload/build.rs
- filpreload/src/lib.rs
- memapi/src/lib.rs
- memapi/src/memorytracking.rs
- memapi/src/mmap.rs
- memapi/src/oom.rs
- memapi/src/rangemap.rs
> Better unsafe usage, and a few lint fixes

- .changelog/383.feature
- .github/workflows/main.yml
- docs/src/README.md
> macOS arm64 wheels

- .changelog/389.bugfix
- Cargo.lock
- filpreload/Cargo.toml
- filpreload/src/_filpreload.c
> Remove jemalloc

- .changelog/395.feature
- .github/dependabot.yml
- .github/workflows/main.yml
- memapi/src/oom.rs
> ARM wheels (WIP)

- .github/workflows/main.yml
- wheels/build-wheels.sh
Fixes #412 (probably, need to validate some more)
Fixes #422
> Test wheels on macOS (and hopefully fix mac wheels while we're at it)

- Cargo.lock
- docs/theme/fonts.css
- filprofiler/_report.py
- memapi/Cargo.toml
Fixes #420 
Maybe #425, need to validate once it's live
> Advertise sciagraph a bit more, and nicer report layout

- docs/src/trying.md
I tested this with a local build.
> fix internal link to install instructions

- CHANGELOG.md
- docs/src/oom.md
- filprofiler/_ipython.py
- filprofiler/_script.py
- tests/test_endtoend.py
> Disable OOM on macOS
